CREATE DATABASE dbGAM
GO

CREATE TABLE MembersGAM
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	lastname VARCHAR(50),
	age INT NOT NULL,
	height DECIMAL(3,2) NOT NULL,
	dob DATETIME NOT NULL
)
GO